name: Node.js CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm
      run: |
        npm install -g npm
        npm --version
    - name: Install dependencies
      run: npm install
    - name: npm ls
      run: npm ls
    - name: Test
      run: npm test
