name: nodejs
on: [pull_request, push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10, 12, 14]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Node.js v${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm
      run: |
        npm install -g npm
        npm --version
    - uses: actions/checkout@v2.3.4
    - name: Install dependencies
      uses: bahmutov/npm-install@v1.4.4
      with:
        useLockFile: false
    - run: npm ls --depth 0
      continue-on-error: true
    - name: Test
      run: npm test
